# This is a basic workflow to help you get started with Actions

name: CI2

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: create env
        id: vars
        run: |
          branch=${GITHUB_REF##*/} 
          echo "::set-output name=GREETING::GREETING_${branch^^}"
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "GREETING is ${{ secrets[steps.vars.outputs.GREETING] }}"
